### ISSUE TITLE
Implement Fee-rate-kit status feature with information based on fee-rate providers

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/blockchain-fee-rate-kit-ios#14]
- Add status info feature with information about fee-rate providers and possible blockchain info details

**Comment by mNizhurin** [comment]
Return array of tuples with structure like this:
```
Bitcoin:
    low: 1
    medium: 4
    high: 13
    date: date of creation
Ethereum:
    low: 13000000000
    medium: 16000000000
    high: 19000000000
    date: date of creation    
etc.
```

In case of error second level must contain plain error:

`error: something went wrong`
